name: 'Yarn Install with cache'
description: 'Doing yarn installs with proper caching'
runs:
  using: 'composite'
  steps:
    - name: 'Setting up Node'
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 'Getting yarn cache directory path'
      id: yarn-cache-dir-path
      working-directory: ./client
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: 'Installing Dependencies'
      working-directory: ./client
      run: yarn install --immutable --inline-builds
      shell: bash
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
        YARN_NM_MODE: 'hardlinks-local'
        HUSKY: '0'
