version: '3.8'
services:
  postgresdb:
    # image: postgres
    hostname: postgresdb-dp-fe
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: dialogporten
    build:
      context: .
      dockerfile: PgDockerfile
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - "5430"
    ports:
      - "5430:5432"

  # migration-job:
  #   depends_on:
  #     - postgresdb
  #   environment:
  #     # - DB_HOST=postgresdb-dp-fe
  #     # - DB_USER=postgres
  #     # - DB_PORT=5432
  #     # - DB_PASSWORD=mysecretpassword
  #     # - DB_NAME=dialogporten
  #     - IS_MIGRATION_JOB=true
  #     - IS_LOCAL=true
  #   build:
  #     context: ./bff-node
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   volumes:
  #     - ./bff-node:/app/   # Map the host app directory to the container's /app
  #   working_dir: /app/

  node-server:
    depends_on:
      - postgresdb
      # - migration-job
    environment:
      - PORT=3000
      - DB_HOST=postgresdb-dp-fe
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=dialogporten
      - IS_LOCAL=true
    build:
      context: ./bff-node
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./bff-node:/app/   # Map the host app directory to the container's /app
    working_dir: /app/
    ports:
      - "3000:3000"  # Map container port to host port
    expose:
      - "3000"
  
  
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client/src:/react/src
    ports:
      - "80:80"  # Map container port to host port
    expose:
      - "80"
    environment:
      - NODE_ENV=development
    depends_on:
    - node-server  # Ensure the backend is up before starting the React app

networks:
  default:
    driver: bridge
    name: dialogporten-frontend-network
