version: '3.8'
services:
  postgresdb:
    image: postgres
    hostname: postgresdb-dp-fe
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: database_development
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - "5430"
    ports:
      - "5430:5432"
  
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client/src:/react/src
    ports:
      - "3000:3000"  # Map container port to host port
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    depends_on:
    - node-server  # Ensure the backend is up before starting the React app

  node-server:
    depends_on:
      - postgresdb
    environment:
      - PORT=3001
      - DB_HOST=postgresdb-dp-fe
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=database_development
    build:
      context: ./bff-node
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./bff-node:/app/   # Map the host app directory to the container's /app
    working_dir: /app/
    ports:
      - "3001:3001"  # Map container port to host port
  
networks:
  default:
    driver: bridge
    name: dialogporten-frontend-network
