services:
  redis:
    container_name: redis
    image: redis:6.0-alpine
    restart: always
    ports:
      - 6379:6379
    command: >
      redis-server --save 20 1 --loglevel warning --requirepass mysecretpassword
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # GUI for checking whats in Redis
  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight
    environment:
      RI_APP_PORT: 80
      RI_APP_HOST: '0.0.0.0'
    ports:
      - 8080:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redisinsight.rule=Host(`redisinsight.localhost`)"
      - "traefik.http.services.redisinsight.loadbalancer.server.port=80"
      - "dave.relativeSubdomain=redisinsight"
      - "dave.icon=devicon-plain:redis-wordmark"
    volumes:
      - redisinsight_cache:/data

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: dialogporten
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 20s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin4.rule=Host(`pgadmin4.localhost`)"
      - "dave.relativeSubdomain=pgadmin4"
      - "dave.icon=simple-icons:postgresql"

volumes:
  pgadmin_data:
  postgres_data:
  redisinsight_cache:
    driver: local
