name: Frontend Tests

on:
  push:
    paths:
      - './**'
      - '.github/workflows/frontend-unit-tests.yml'
      - 'package.json'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: 'Typechecking and linting'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: 'Checking Out Code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Installing Dependencies'
        uses: ./.github/actions/yarn-install

      - name: 'Doing the typecheck'
        run: yarn typecheck

      - name: 'Running Eslint'
        run: yarn lint

  test:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking Out Code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Installing Dependencies'
        uses: ./.github/actions/yarn-install

      - name: 'Running Unit Tests'
        run: yarn test

  build:
    name: 'Building'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking Out Code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Installing Dependencies'
        uses: ./.github/actions/yarn-install

      - name: 'Building'
        run: yarn build
