export enum PageRoutes {
  inbox = '/',
  inboxItem = '/inbox/:id',
  sent = '/sent',
  drafts = '/drafts',
  savedSearches = '/saved-searches',
  archive = '/archive',
  bin = '/bin',
  profile = '/profile',
  partiesOverview = '/profile/parties',
  authorize = '/profile/authorize',
  access = '/profile/access',
  notifications = '/profile/notifications',
  settings = '/profile/settings',
  activities = '/profile/activities',
  error = '/error',
}
