name: 'pnpm install with cache'
description: 'Doing installs'
runs:
  using: 'composite'
  steps:
    - name: 'Setting up Node'
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: .node-version
        registry-url: 'https://registry.npmjs.org'

    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Install dependencies
      shell: bash
      run: pnpm install
