export const QUERY_KEYS = {
  DIALOG_BY_ID: 'dialogById',
  PARTIES: 'parties',
  PARTIES_EMPTY_LIST: 'partiesEmptyList',
  SELECTED_PARTIES: 'selectedParties',
  ALL_ORGANIZATIONS_SELECTED: 'allOrganizationsSelected',
  SEARCH_DIALOGS: 'searchDialogs',
  SEARCH_AUTOCOMPLETE_DIALOGS: 'searchAutocompleteDialogs',
  DIALOGS: 'dialogs',
  COUNT_DIALOGS: 'countDialogs',
  MAIN_CONTENT_REFERENCE: 'mainContentReference',
  SAVED_SEARCHES: 'savedSearches',
  PROFILE: 'profile',
  NOTIFICATIONSETTINGSFORPARTY: 'notificationsettingsforparty',
  PROFILE_PARTIES_WITH_NOTIFICATION_SETTINGS: 'profilePartiesWithNotificationSettings',
  ORGANIZATIONS: 'organizations',
  SEARCH_VALUE: 'searchValue',
  ENTERED_SEARCH_VALUE: 'enteredSearchValue',
  SET_ARCHIVE_LABEL_LOADING: 'setArchiveLabelLoading',
  SET_DELETE_LABEL_LOADING: 'setDeleteLabelLoading',
  SET_UNDO_LABEL_LOADING: 'setUndoLabelLoading',
  ERROR_STATE: 'errorState',
  SHOW_TOUR: 'showTour',
};
