name: DeployTestFrontend
on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy Frontend to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts

      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      #
      - name: 'Get resource group with PowerShell action'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup
          azPSVersion: 'latest'

      - name: Deploy infrastructure
        id: bicep
        shell: pwsh
        run: >
          .azure/deployBicep.ps1 
          -environment test
          -gitSha ${{github.sha}} 
          -subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout
