name: Build Push to ghcr and deploy to AT
on:
  workflow_dispatch:
  push:
    branches: ['*']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: digdir/dialogporten-frontend
  CONTAINER_APP_CONTAINER_NAME: dialogporten
  CONTAINER_APP_NAME: altinn-dev-dialogporten-app
  CONTAINER_APP_RESOURCE_GROUP_NAME: Dialogporten-Test
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-at21:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Azure Login
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: >
            az config set extension.use_dynamic_install=yes_without_prompt

            az containerapp update \
              --name ${{ env.CONTAINER_APP_NAME }} \
              --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} \
              --resource-group ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }} \
              --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: logout
        run: >
          az logout
