name: WorkflowTest

on:
  workflow_dispatch:
  push:
    branches: [main]
    #paths: [ src/**, tests/**, .github/workflows/** ]

jobs:
  build-and-test:
    uses: ./.github/workflows/BuildAndRunTestsFrontend.yml
    secrets: inherit
    with:
      environment: test

  publish:
    needs: [build-and-test]
    uses: ./.github/workflows/PublishTestFrontend.yml
    with:
      publishArtifacts: true

  deployTest:
    needs: [publish]
    uses: ./.github/workflows/DeployTestFrontend.yml
    secrets: inherit
    with:
      environment: test
