name: Upload Source Maps to Application Insights

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      ref:
        description: "The branch or tag ref to use. Using default checkout ref if not provided."
        required: false
        default: ${{ github.ref }}
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_SOURCE_MAPS_STORAGE_ACCOUNT_NAME:
        description: "The Azure Storage Account name for source maps"
        required: true
      AZURE_SOURCE_MAPS_CONTAINER_NAME:
        description: "The Azure Blob Storage container name for source maps"
        required: true

jobs:
  upload-source-maps:
    name: Upload source maps to Application Insights (${{ inputs.environment }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Build frontend with source maps
        run: pnpm --filter frontend run build
        working-directory: ${{ github.workspace }}

      - name: Azure Login
        uses: ./.github/actions/azure-login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload source maps to blob storage
        id: upload-source-maps
        run: |
          cd packages/frontend/dist/assets
          
          # Upload each source map file with version prefix
          for mapfile in *.map; do
            if [ -f "$mapfile" ]; then
              echo "Uploading $mapfile..."
              
              # Upload with version prefix
              az storage blob upload \
                --account-name "${{ secrets.AZURE_SOURCE_MAPS_STORAGE_ACCOUNT_NAME }}" \
                --container-name "${{ secrets.AZURE_SOURCE_MAPS_CONTAINER_NAME }}" \
                --name "${{ inputs.version }}/$mapfile" \
                --file "$mapfile" \
                --auth-mode login
              
              echo "Uploaded $mapfile successfully"
            fi
          done
          
          echo "source_maps_uploaded=true" >> $GITHUB_OUTPUT

      - name: Logout from Azure
        if: always()
        continue-on-error: true
        run: az logout 